
package org.trialversionv1.main;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenerateSerialKey", targetNamespace = "http://main.trialVersionv1.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenerateSerialKey {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateKey", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.GenerateKey")
    @ResponseWrapper(localName = "generateKeyResponse", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.GenerateKeyResponse")
    @Action(input = "http://main.trialVersionv1.org/GenerateSerialKey/generateKeyRequest", output = "http://main.trialVersionv1.org/GenerateSerialKey/generateKeyResponse")
    public Boolean generateKey(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subscriptionRate", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.SubscriptionRate")
    @ResponseWrapper(localName = "subscriptionRateResponse", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.SubscriptionRateResponse")
    @Action(input = "http://main.trialVersionv1.org/GenerateSerialKey/subscriptionRateRequest", output = "http://main.trialVersionv1.org/GenerateSerialKey/subscriptionRateResponse")
    public List<String> subscriptionRate();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptExpDate", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.EncryptExpDate")
    @ResponseWrapper(localName = "encryptExpDateResponse", targetNamespace = "http://main.trialVersionv1.org/", className = "org.trialversionv1.main.EncryptExpDateResponse")
    @Action(input = "http://main.trialVersionv1.org/GenerateSerialKey/encryptExpDateRequest", output = "http://main.trialVersionv1.org/GenerateSerialKey/encryptExpDateResponse")
    public String encryptExpDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        float arg2);

}
