
package org.trialversionv1.main;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenerateSerialKeyService", targetNamespace = "http://main.trialVersionv1.org/", wsdlLocation = "http://viper:8080/TrialVersionWS_v.1Server/GenerateSerialKeyService?wsdl")
public class GenerateSerialKeyService
    extends Service
{

    private final static URL GENERATESERIALKEYSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERATESERIALKEYSERVICE_EXCEPTION;
    private final static QName GENERATESERIALKEYSERVICE_QNAME = new QName("http://main.trialVersionv1.org/", "GenerateSerialKeyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://viper:8080/TrialVersionWS_v.1Server/GenerateSerialKeyService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERATESERIALKEYSERVICE_WSDL_LOCATION = url;
        GENERATESERIALKEYSERVICE_EXCEPTION = e;
    }

    public GenerateSerialKeyService() {
        super(__getWsdlLocation(), GENERATESERIALKEYSERVICE_QNAME);
    }

    public GenerateSerialKeyService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERATESERIALKEYSERVICE_QNAME, features);
    }

    public GenerateSerialKeyService(URL wsdlLocation) {
        super(wsdlLocation, GENERATESERIALKEYSERVICE_QNAME);
    }

    public GenerateSerialKeyService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERATESERIALKEYSERVICE_QNAME, features);
    }

    public GenerateSerialKeyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenerateSerialKeyService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenerateSerialKey
     */
    @WebEndpoint(name = "GenerateSerialKeyPort")
    public GenerateSerialKey getGenerateSerialKeyPort() {
        return super.getPort(new QName("http://main.trialVersionv1.org/", "GenerateSerialKeyPort"), GenerateSerialKey.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenerateSerialKey
     */
    @WebEndpoint(name = "GenerateSerialKeyPort")
    public GenerateSerialKey getGenerateSerialKeyPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://main.trialVersionv1.org/", "GenerateSerialKeyPort"), GenerateSerialKey.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERATESERIALKEYSERVICE_EXCEPTION!= null) {
            throw GENERATESERIALKEYSERVICE_EXCEPTION;
        }
        return GENERATESERIALKEYSERVICE_WSDL_LOCATION;
    }

}
